# ALIASES
alias please="sudo"
alias up="cd ../"
alias rmrf="rm -rf"
alias mkdir="mkdir -p"
alias cp="cp -r"
alias ls="exa -l"
alias hostname="echo 'maxm-x220'"
alias term="urxvt"
alias pacman="sudo pacman"
alias update="pacman -Syu"
alias systemctl="sudo systemctl"
alias :q="sudo systemctl poweroff"
alias reboot="sudo reboot"
